#Laboratory №2
DROP DATABASE IF EXISTS concerts;

CREATE DATABASE concerts;

USE concerts;

CREATE TABLE concert_hall
(
    HALL_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
    HALL_NAME   VARCHAR(32)  NOT NULL,
    ADDRESS     VARCHAR(255) NOT NULL,
    SITS_NUMBER INT          NOT NULL
);

INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('NORTH', '0x111', '150');
INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('SOUSE', '0x111', '258');
INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('WEST', '0x111', '367');
INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('EAST', '0x111', '127');
INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('AMERICA', '0x222', '215');

ALTER TABLE concert_hall
    ADD `TEMP_COLUMN` INT;

ALTER TABLE concert_hall
    MODIFY ADDRESS VARCHAR(255) AFTER TEMP_COLUMN;

ALTER TABLE concert_hall
    DROP COLUMN TEMP_COLUMN;

CREATE TABLE DELETING_TABLE
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DROP TABLE IF EXISTS DELETING_TABLE;