#Laboratory №3
USE concerts;

#3
INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('RUSSIA', '0x222', '236');

INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('VICTORY', '0x333', '536');

INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('SEVASTOPOL', '0x444', '653');

INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('KALAMITA', '0x444', '229');

INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('BALAKLAVA', '0x444', '897');

#4

#4.1
INSERT INTO concert_hall(HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('KHERSONES', '0x444', '897');

#4.2
INSERT INTO concert_hall(ADDRESS, SITS_NUMBER, HALL_NAME)
VALUES ('0x444', '897', 'UKRAINE');

#4.3
INSERT INTO concert_hall
    (HALL_NAME, ADDRESS, SITS_NUMBER)
VALUES ('OLIMPIC', '0x115', '8000'),
       ('JANKONG', '0x333', '12'),
       ('GARLAND', '0x333', '369');

#5
UPDATE concert_hall
SET ADDRESS = '0x115'
ORDER BY HALL_NUMBER DESC
LIMIT 1;

#6
UPDATE concert_hall
SET SITS_NUMBER = '200'
WHERE HALL_NUMBER = 13;

#7
DELETE
FROM concert_hall
WHERE ADDRESS = '0x444';